---
################################################################################
# NIST 800-53 IA-7 Cryptographic Module Authentication - Ansible Playbook
#
# Description:
#   Cross-platform validation of FIPS 140-2/140-3 compliance for cryptographic
#   module authentication per NIST SP 800-53 Rev 5 IA-7.
#
#   Supports: Windows Server 2019/2022, RHEL 8, Ubuntu 22.04
#
# Usage:
#   ansible-playbook -i inventory.ini ia-7_ansible.yml
#   ansible-playbook -i inventory.ini ia-7_ansible.yml --check  # Dry run
#   ansible-playbook -i inventory.ini ia-7_ansible.yml -e "output_dir=/tmp/ia7_reports"
#
# Variables:
#   output_dir: Directory for compliance reports (default: /tmp/ia7_compliance)
#
# Author: LOVELESS (QA Specialist)
# Version: 1.0
# Read-only: YES - No system modifications
# Idempotent: YES - Safe to run multiple times
# Zero hallucination tolerance: All checks verify actual system state
################################################################################

- name: NIST 800-53 IA-7 Cryptographic Module Authentication Validation
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    output_dir: "/tmp/ia7_compliance"
    control_id: "IA-7"
    control_name: "Cryptographic Module Authentication"

  tasks:
    - name: Create output directory for compliance reports
      file:
        path: "{{ output_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: yes

    - name: Initialize compliance report structure
      set_fact:
        compliance_report:
          control_id: "{{ control_id }}"
          control_name: "{{ control_name }}"
          timestamp: "{{ ansible_date_time.iso8601 }}"
          hostname: "{{ ansible_hostname }}"
          os_family: "{{ ansible_os_family }}"
          os_distribution: "{{ ansible_distribution }}"
          os_version: "{{ ansible_distribution_version }}"
          compliant: true
          findings: []
          evidence: {}
          errors: []

    ############################################################################
    # Windows Server Validation
    ############################################################################

    - name: Windows - Check FIPS mode enablement (registry)
      win_reg_stat:
        path: HKLM:\System\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy
        name: Enabled
      register: win_fips_reg
      when: ansible_os_family == "Windows"

    - name: Windows - Evaluate FIPS mode compliance
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'compliant': false,
          'findings': compliance_report.findings + [{
            'check': 'Windows FIPS Mode',
            'status': 'FAIL',
            'severity': 'HIGH',
            'finding': 'FIPS mode not enabled in registry',
            'remediation': 'Enable via GPO: System cryptography: Use FIPS compliant algorithms = Enabled',
            'stig_id': 'V-205842'
          }]
        }) }}"
      when:
        - ansible_os_family == "Windows"
        - win_fips_reg.exists and win_fips_reg.value != 1

    - name: Windows - Record FIPS mode evidence
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'evidence': compliance_report.evidence | combine({'fips_mode_windows': 'enabled'})
        }) }}"
      when:
        - ansible_os_family == "Windows"
        - win_fips_reg.exists and win_fips_reg.value == 1

    - name: Windows - Check TLS 1.2 enablement
      win_reg_stat:
        path: "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.2\\Server"
        name: Enabled
      register: win_tls12_reg
      when: ansible_os_family == "Windows"

    - name: Windows - Record TLS 1.2 evidence
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'evidence': compliance_report.evidence | combine({'tls_12_enabled': (win_tls12_reg.value == 1) | string})
        }) }}"
      when:
        - ansible_os_family == "Windows"
        - win_tls12_reg.exists

    - name: Windows - Check for weak SSL/TLS protocols
      win_reg_stat:
        path: "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\{{ item }}\\Server"
        name: Enabled
      register: win_weak_protocols
      loop:
        - "SSL 2.0"
        - "SSL 3.0"
        - "TLS 1.0"
        - "TLS 1.1"
      when: ansible_os_family == "Windows"

    - name: Windows - Evaluate weak protocol compliance
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'compliant': false,
          'findings': compliance_report.findings + [{
            'check': 'Windows Weak Protocols',
            'status': 'FAIL',
            'severity': 'HIGH',
            'finding': 'Weak protocol ' + item.item + ' is enabled',
            'remediation': 'Disable weak protocols via registry or Group Policy'
          }]
        }) }}"
      loop: "{{ win_weak_protocols.results }}"
      when:
        - ansible_os_family == "Windows"
        - item.exists and item.value != 0

    - name: Windows - Check bcryptprimitives.dll presence
      win_stat:
        path: "C:\\Windows\\System32\\bcryptprimitives.dll"
      register: win_bcrypt_dll
      when: ansible_os_family == "Windows"

    - name: Windows - Record bcryptprimitives evidence
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'evidence': compliance_report.evidence | combine({'bcryptprimitives_present': 'yes'})
        }) }}"
      when:
        - ansible_os_family == "Windows"
        - win_bcrypt_dll.stat.exists

    ############################################################################
    # RHEL/CentOS Validation
    ############################################################################

    - name: RHEL - Check FIPS mode kernel enablement
      command: cat /proc/sys/crypto/fips_enabled
      register: rhel_fips_enabled
      changed_when: false
      failed_when: false
      when: ansible_os_family == "RedHat"

    - name: RHEL - Evaluate FIPS mode compliance
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'compliant': false,
          'findings': compliance_report.findings + [{
            'check': 'RHEL FIPS Mode',
            'status': 'FAIL',
            'severity': 'HIGH',
            'finding': 'FIPS mode not enabled. /proc/sys/crypto/fips_enabled = ' + rhel_fips_enabled.stdout,
            'remediation': 'Enable FIPS: fips-mode-setup --enable && reboot',
            'stig_id': 'RHEL-08-010160'
          }]
        }) }}"
      when:
        - ansible_os_family == "RedHat"
        - rhel_fips_enabled.stdout | default('0') != '1'

    - name: RHEL - Record FIPS mode evidence
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'evidence': compliance_report.evidence | combine({'fips_mode_rhel': 'enabled'})
        }) }}"
      when:
        - ansible_os_family == "RedHat"
        - rhel_fips_enabled.stdout | default('0') == '1'

    - name: RHEL - Check dracut-fips package
      command: rpm -q dracut-fips
      register: rhel_dracut_fips
      changed_when: false
      failed_when: false
      when: ansible_os_family == "RedHat"

    - name: RHEL - Evaluate dracut-fips compliance
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'compliant': false,
          'findings': compliance_report.findings + [{
            'check': 'RHEL dracut-fips Package',
            'status': 'FAIL',
            'severity': 'HIGH',
            'finding': 'dracut-fips package not installed',
            'remediation': 'Install: yum install dracut-fips && dracut -f && reboot'
          }]
        }) }}"
      when:
        - ansible_os_family == "RedHat"
        - rhel_dracut_fips.rc != 0

    - name: RHEL - Check system crypto-policy
      command: update-crypto-policies --show
      register: rhel_crypto_policy
      changed_when: false
      failed_when: false
      when: ansible_os_family == "RedHat"

    - name: RHEL - Evaluate crypto-policy compliance
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'compliant': false,
          'findings': compliance_report.findings + [{
            'check': 'RHEL Crypto-Policy',
            'status': 'FAIL',
            'severity': 'HIGH',
            'finding': 'System crypto-policy not set to FIPS. Current: ' + rhel_crypto_policy.stdout,
            'remediation': 'Set FIPS policy: update-crypto-policies --set FIPS && reboot'
          }]
        }) }}"
      when:
        - ansible_os_family == "RedHat"
        - rhel_crypto_policy.stdout | default('') != 'FIPS'

    - name: RHEL - Record crypto-policy evidence
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'evidence': compliance_report.evidence | combine({'crypto_policy': rhel_crypto_policy.stdout | default('unknown')})
        }) }}"
      when: ansible_os_family == "RedHat"

    - name: RHEL - Check PAM sha512 hashing
      shell: grep -E "^password.*pam_unix.so.*sha512" /etc/pam.d/password-auth
      register: rhel_pam_sha512
      changed_when: false
      failed_when: false
      when: ansible_os_family == "RedHat"

    - name: RHEL - Evaluate PAM sha512 compliance
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'compliant': false,
          'findings': compliance_report.findings + [{
            'check': 'RHEL PAM SHA-512',
            'status': 'FAIL',
            'severity': 'HIGH',
            'finding': '/etc/pam.d/password-auth missing sha512 option for pam_unix.so',
            'remediation': 'Add sha512 to pam_unix.so in /etc/pam.d/password-auth',
            'stig_id': 'RHEL-08-010160'
          }]
        }) }}"
      when:
        - ansible_os_family == "RedHat"
        - rhel_pam_sha512.rc != 0

    - name: RHEL - Check SSH FIPS ciphers
      shell: grep "^Ciphers" /etc/ssh/sshd_config | grep -E "3des|arcfour|blowfish|cast128"
      register: rhel_ssh_weak_ciphers
      changed_when: false
      failed_when: false
      when: ansible_os_family == "RedHat"

    - name: RHEL - Evaluate SSH cipher compliance
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'compliant': false,
          'findings': compliance_report.findings + [{
            'check': 'RHEL SSH Ciphers',
            'status': 'FAIL',
            'severity': 'HIGH',
            'finding': 'Non-FIPS ciphers detected in sshd_config',
            'remediation': 'Configure Ciphers aes256-ctr,aes192-ctr,aes128-ctr in /etc/ssh/sshd_config',
            'stig_id': 'RHEL-07-040110'
          }]
        }) }}"
      when:
        - ansible_os_family == "RedHat"
        - rhel_ssh_weak_ciphers.rc == 0

    ############################################################################
    # Ubuntu/Debian Validation
    ############################################################################

    - name: Ubuntu - Check Ubuntu Advantage FIPS status
      command: ua security status fips
      register: ubuntu_ua_fips
      changed_when: false
      failed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Ubuntu - Record UA FIPS evidence
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'evidence': compliance_report.evidence | combine({
            'ua_fips_status': 'enabled' if 'enabled' in ubuntu_ua_fips.stdout | default('') else 'not_enabled'
          })
        }) }}"
      when: ansible_distribution == "Ubuntu"

    - name: Ubuntu - Check PAM sha512 hashing
      shell: grep -E "^password.*pam_unix.so.*sha512" /etc/pam.d/common-password
      register: ubuntu_pam_sha512
      changed_when: false
      failed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Ubuntu - Evaluate PAM sha512 compliance
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'compliant': false,
          'findings': compliance_report.findings + [{
            'check': 'Ubuntu PAM SHA-512',
            'status': 'FAIL',
            'severity': 'HIGH',
            'finding': '/etc/pam.d/common-password missing sha512 option for pam_unix.so',
            'remediation': 'Add sha512 to pam_unix.so in /etc/pam.d/common-password'
          }]
        }) }}"
      when:
        - ansible_distribution == "Ubuntu"
        - ubuntu_pam_sha512.rc != 0

    - name: Ubuntu - Check OpenSSL version
      command: openssl version
      register: ubuntu_openssl_version
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Ubuntu - Record OpenSSL evidence
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'evidence': compliance_report.evidence | combine({'openssl_version': ubuntu_openssl_version.stdout | default('unknown')})
        }) }}"
      when: ansible_distribution == "Ubuntu"

    - name: Ubuntu - Check for weak SSH ciphers
      shell: grep "^Ciphers" /etc/ssh/sshd_config 2>/dev/null | grep -E "3des|arcfour|blowfish|cast128|chacha20" || true
      register: ubuntu_ssh_weak_ciphers
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Ubuntu - Evaluate SSH cipher compliance
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'compliant': false,
          'findings': compliance_report.findings + [{
            'check': 'Ubuntu SSH Ciphers',
            'status': 'FAIL',
            'severity': 'HIGH',
            'finding': 'Non-FIPS ciphers detected in sshd_config',
            'remediation': 'Configure Ciphers aes256-ctr,aes192-ctr,aes128-ctr,aes256-gcm@openssh.com,aes128-gcm@openssh.com'
          }]
        }) }}"
      when:
        - ansible_distribution == "Ubuntu"
        - ubuntu_ssh_weak_ciphers.stdout | length > 0

    - name: Ubuntu - Check AppArmor status
      command: aa-status --enabled
      register: ubuntu_apparmor_status
      changed_when: false
      failed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Ubuntu - Record AppArmor evidence
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'evidence': compliance_report.evidence | combine({'apparmor_enabled': 'yes' if ubuntu_apparmor_status.rc == 0 else 'no'})
        }) }}"
      when: ansible_distribution == "Ubuntu"

    ############################################################################
    # Cross-Platform SSH Validation
    ############################################################################

    - name: All - Check SSH weak MACs
      shell: grep "^MACs" /etc/ssh/sshd_config 2>/dev/null | grep -E "md5|96|umac-64" || true
      register: ssh_weak_macs
      changed_when: false
      when: ansible_os_family in ["RedHat", "Debian"]

    - name: All - Evaluate SSH MAC compliance
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'compliant': false,
          'findings': compliance_report.findings + [{
            'check': 'SSH MACs',
            'status': 'FAIL',
            'severity': 'HIGH',
            'finding': 'Weak MACs detected in sshd_config',
            'remediation': 'Configure MACs hmac-sha2-256,hmac-sha2-512'
          }]
        }) }}"
      when:
        - ansible_os_family in ["RedHat", "Debian"]
        - ssh_weak_macs.stdout | length > 0

    ############################################################################
    # Report Generation
    ############################################################################

    - name: Calculate compliance summary
      set_fact:
        compliance_report: "{{ compliance_report | combine({
          'summary': {
            'findings_count': compliance_report.findings | length,
            'errors_count': compliance_report.errors | length,
            'compliance_status': 'COMPLIANT' if compliance_report.compliant else 'NON-COMPLIANT'
          }
        }) }}"

    - name: Generate compliance report filename
      set_fact:
        report_filename: "{{ output_dir }}/ia7_{{ ansible_hostname }}_{{ ansible_date_time.epoch }}.json"

    - name: Write compliance report to file
      copy:
        content: "{{ compliance_report | to_nice_json }}"
        dest: "{{ report_filename }}"
      delegate_to: localhost

    - name: Display compliance summary
      debug:
        msg: |
          ============================================
          IA-7 COMPLIANCE SUMMARY: {{ ansible_hostname }}
          ============================================
          Status: {{ compliance_report.summary.compliance_status }}
          Findings: {{ compliance_report.summary.findings_count }}
          Errors: {{ compliance_report.summary.errors_count }}
          Report: {{ report_filename }}
          ============================================

    - name: Fail playbook if non-compliant
      fail:
        msg: "Host {{ ansible_hostname }} is NON-COMPLIANT with IA-7. See report: {{ report_filename }}"
      when: not compliance_report.compliant
